### ISSUE TITLE
reverse result

### ISSUE THREAD

**Issue by vando2108** [RobinXL/inkml2img#3] opened 2021-07-23 08:12 UTC
I pulled your code and run it in my computer. 
![image](https://user-images.githubusercontent.com/35914996/126752349-f19829de-1bd4-4150-a3a1-cf51ac963b28.png)s is my This result, it was reversed. How I can make that look like your result? 
Thanks you!

**Comment by Benjamin-Loison** [comment] 2022-01-28 01:44
Hello,

1. the image is upside down: convert -flip upsideDown.png notUpsideDown.png
2. remove the key: convert notUpsideDown.png -fill white +opaque "#284054" noKey.png
3. you change the #284054 to black: convert noKey.png -fill black -opaque "#284054" blackFormula.png
4. go through the inkml file check the extremum values for x and y and then transform the image accordingly using nearest neighbor interpolation algorithm:

from PIL import Image

im = Image.open('blackFormula.png')
im = im.resize((deltaX, deltaY), Image.NEAREST)
im.save('200923-1556-49.png')

**Comment by RobinXL** [comment] 2022-04-04 23:11
The issue is caused by python3 vs python2 `matplotlib` library. It's now fixed with the update.

**Closed as completed by RobinXL** 2022-04-04 23:11 UTC
